// Generated by tools/build-tips.py from the Omarchy manual. Do not edit.
.pragma library

var tips = [
 {
  "page": "Getting Started",
  "section": "Installing for another owner",
  "url": "https://omarchy.org/manual/getting-started/",
  "text": "Hit `Ctrl + C` on the very first screen of the installer (the keyboard selection), and Omarchy will offer to prepare the machine for another owner instead."
 },
 {
  "page": "Getting Started",
  "section": "No-encryption installations",
  "url": "https://omarchy.org/manual/getting-started/",
  "text": "You can hit `Ctrl + C` on the disk formatting confirmation to switch to an encryption-less installation."
 },
 {
  "page": "Coming From Mac or Windows",
  "section": "Super is the center of everything",
  "url": "https://omarchy.org/manual/coming-from-mac-or-windows/",
  "text": "Your Spotlight or Raycast or Start-menu reflex becomes `Super + Space`."
 },
 {
  "page": "Coming From Mac or Windows",
  "section": "There's no dock and no desktop icons",
  "url": "https://omarchy.org/manual/coming-from-mac-or-windows/",
  "text": "Apps start from a hotkey (`Super + Return` for the terminal, `Super + Shift + Return` for the browser, and `Super + K` for a list of everything that's mapped) or from the menu."
 },
 {
  "page": "Coming From Mac or Windows",
  "section": "Windows place themselves",
  "url": "https://omarchy.org/manual/coming-from-mac-or-windows/",
  "text": "When you genuinely need a floating window, `Super + T` toggles the active one out of the tiling (and back)."
 },
 {
  "page": "Coming From Mac or Windows",
  "section": "Windows place themselves",
  "url": "https://omarchy.org/manual/coming-from-mac-or-windows/",
  "text": "Workspaces will feel familiar: they're macOS Spaces or Windows virtual desktops, except you'll actually use them, because `Super + 1/2/3/4` jumps straight to one and `Super + Shift + 1/2/3/4` sends the active window there."
 },
 {
  "page": "Coming From Mac or Windows",
  "section": "Copy and paste just work",
  "url": "https://omarchy.org/manual/coming-from-mac-or-windows/",
  "text": "Omarchy gives you `Super + C`, `Super + X`, and `Super + V`, and they work everywhere, including the terminal."
 },
 {
  "page": "Coming From Mac or Windows",
  "section": "Copy and paste just work",
  "url": "https://omarchy.org/manual/coming-from-mac-or-windows/",
  "text": "Windows folks: your Win + V clipboard history lives on `Super + Ctrl + V`, and it holds images as well as text."
 },
 {
  "page": "Coming From Mac or Windows",
  "section": "Some things really are different",
  "url": "https://omarchy.org/manual/coming-from-mac-or-windows/",
  "text": "`Super + W`, or `Super + Q`, if that's the finger memory you arrived with, means gone."
 },
 {
  "page": "Coming From Mac or Windows",
  "section": "Give it two weeks",
  "url": "https://omarchy.org/manual/coming-from-mac-or-windows/",
  "text": "Skim the hotkeys chapter once, and whenever you blank on a binding, hit `Super + K`, it shows you all of them."
 },
 {
  "page": "Navigation",
  "section": "",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "You start the terminal with `Super + Return` and a browser with `Super + Shift + Return`."
 },
 {
  "page": "Navigation",
  "section": "",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "Hit `Super + J` again to return them to their side-by-side positions."
 },
 {
  "page": "Navigation",
  "section": "",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "You can tile it using `Super + T` (and hit that again to make it floating again)."
 },
 {
  "page": "Navigation",
  "section": "",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "You navigate between the window you want to be active with `Super + Arrow`."
 },
 {
  "page": "Navigation",
  "section": "",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "If you hit `Super + Shift + 2`, you'll move the current focused application onto the second workspace."
 },
 {
  "page": "Navigation",
  "section": "",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "(And `Super + Shift + Alt + 2` will move the current focused application onto the second workspace without switching to it)."
 },
 {
  "page": "Navigation",
  "section": "",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "If you hold down `Super` and use the mouse to click on a window, you'll be able to rearrange where it sits."
 },
 {
  "page": "Navigation",
  "section": "",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "If you hold `Super` and use the right button on the mouse, you can freely resize the window."
 },
 {
  "page": "Navigation",
  "section": "",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "You close a window on `Super + W` or `Super + Q` (and close all windows on `Ctrl + Alt + Delete`)."
 },
 {
  "page": "Navigation",
  "section": "",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "You can also go full screen with `Super + F` or even just full-width (keeping the top bar) with `Super + Alt + F` or full-screen within a window with `Super + Ctrl + F` (good for YouTube!)."
 },
 {
  "page": "Navigation",
  "section": "Dwindle vs scrolling layout",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "You turn a single workspace into this layout via `Super + L`."
 },
 {
  "page": "Navigation",
  "section": "Grouping windows",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "Windows can be grouped using `Super + G`."
 },
 {
  "page": "Navigation",
  "section": "Grouping windows",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "You can move between these grouped windows using `Super + Ctrl + Arrow Left/Right` or `Super + Alt + 1/2/3/4` to go directly to grouped window in order."
 },
 {
  "page": "Navigation",
  "section": "Grouping windows",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "You can move a window out of the grouping with `Super + Alt + G` or disassemble the entire group by hitting `Super + G` again."
 },
 {
  "page": "Navigation",
  "section": "Grouping windows",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "Finally, you can move windows outside the group into it with `Super + Alt + Arrows`."
 },
 {
  "page": "Navigation",
  "section": "Popping windows",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "You can pop a window out of its workspace allocation with `Super + O`."
 },
 {
  "page": "Navigation",
  "section": "Scratchpad workspace",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "Toggle it with `Super + Grave` or `Super + S`, and place a window there using `Super + Shift + Grave` or `Super + Alt + S`."
 },
 {
  "page": "Navigation",
  "section": "Scratchpad workspace",
  "url": "https://omarchy.org/manual/navigation/",
  "text": "To move a window off the scratchpad, send it directly to another workspace with something like `Super + Shift + 1`."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Menu widget in the bar: omarchy menu."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Right-click the Menu widget in the bar: new terminal."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Workspaces widget in the bar: focus that workspace."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Clock widget in the bar: calendar popup."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Right-click the Clock widget in the bar: cycle the label format."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Middle-click the Clock widget in the bar: timezone picker."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Weather widget in the bar: forecast popup."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Right-click the Weather widget in the bar: full weather as a notification."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Middle-click the Weather widget in the bar: refresh."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Audio widget in the bar: audio panel."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Right-click the Audio widget in the bar: mute."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Middle-click the Audio widget in the bar: panel."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Scroll on the Audio widget in the bar: volume."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Microphone widget in the bar: mute the mic."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Middle-click the Microphone widget in the bar: audio panel."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Scroll on the Microphone widget in the bar: input volume."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Network widget in the bar: network panel."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Bluetooth widget in the bar: bluetooth panel."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Right-click the Bluetooth widget in the bar: toggle the radio."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Display widget in the bar: display panel."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Scroll on the Display widget in the bar: brightness."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Power widget in the bar: power panel."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Right-click the Power widget in the bar: toggle the battery percentage."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Media widget in the bar: play/pause."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Right-click the Media widget in the bar: cover-art popup."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Middle-click the Media widget in the bar: next."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Scroll on the Media widget in the bar: prev/next."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Agents widget in the bar: agents panel."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Right-click the Agents widget in the bar: launch your agent."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Middle-click the Agents widget in the bar: next subscription."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Tray widget in the bar: hover to reveal the drawer."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Right-click the Tray widget in the bar: right on the chevron to manage."
 },
 {
  "page": "The Top Bar",
  "section": "Clicking around",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "Click the Omarchy update widget in the bar: run the update."
 },
 {
  "page": "The Top Bar",
  "section": "The panels",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "`Super + Ctrl + A`: Audio"
 },
 {
  "page": "The Top Bar",
  "section": "The panels",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "`Super + Ctrl + W`: Network"
 },
 {
  "page": "The Top Bar",
  "section": "The panels",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "`Super + Ctrl + B`: Bluetooth"
 },
 {
  "page": "The Top Bar",
  "section": "The panels",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "`Super + Ctrl + D`: Display"
 },
 {
  "page": "The Top Bar",
  "section": "The panels",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "`Super + Ctrl + P`: Power"
 },
 {
  "page": "The Top Bar",
  "section": "The panels",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "`Super + Ctrl + Alt + D`: Calendar"
 },
 {
  "page": "The Top Bar",
  "section": "The panels",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "`Super + Ctrl + 1-9`: Toggle the nth panel in the right section"
 },
 {
  "page": "The Top Bar",
  "section": "The panels",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "`Super + Ctrl + 1-9` counts panels left to right in the right section, skipping the tray since it has no panel of its own."
 },
 {
  "page": "The Top Bar",
  "section": "Hiding the bar",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "`Super + Shift + Space` toggles the bar off and back on without killing the shell, panels and hotkeys keep working, you just get the pixels back."
 },
 {
  "page": "The Top Bar",
  "section": "The config file",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "The moment you drag a widget, run `omarchy bar`, or edit the file yourself, you own it, there's no deep merge, so new default widgets in future Omarchy releases won't appear on your bar automatically."
 },
 {
  "page": "The Top Bar",
  "section": "The config file",
  "url": "https://omarchy.org/manual/the-top-bar/",
  "text": "`omarchy bar defaults` puts the shipped layout back whenever you want a clean slate."
 },
 {
  "page": "Themes",
  "section": "",
  "url": "https://omarchy.org/manual/themes/",
  "text": "You can select between them via Style > Theme in the Omarchy Menu (`Super + Space`) or hop directly to the theme selector using `Super + Ctrl + Shift + Space`."
 },
 {
  "page": "Themes",
  "section": "",
  "url": "https://omarchy.org/manual/themes/",
  "text": "Themes have a set of background images that you can pick between using `Super + Ctrl + Space`."
 },
 {
  "page": "Hotkeys",
  "section": "",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "You can see all the main keyboard bindings with `Super + K` (Tmux bindings with `Super + Alt + K` and Herdr bindings with `Super + Ctrl + K`)."
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Space`: Omarchy menu (apps and everything else)"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + Space`: Apps menu"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Escape`: System menu (suspend, restart, etc)"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + L`: Lock computer"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + W` or `Super + Q`: Close window"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + Alt + Del`: Close all windows"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + T`: Toggle window between tiling/floating"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + J`: Toggle window position (horizontal/vertical)"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + O`: Toggle popping window into sticky'n'floating"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + L`: Toggle between dwindle and scrolling layout"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + P`: Toggle pseudo window style (natural v stretch)"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + F`: Go full screen"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + F`: Go full width"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + F`: Go full screen inside window"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + 1/2/3/4`: Jump to specific workspace"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Tab`: Jump to next workspace"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Tab`: Jump to previous workspace"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Tab`: Jump to former workspace"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + 1/2/3/4`: Move window to workspace"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Alt + 1/2/3/4`: Move window to workspace without following"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + S` / `Super + Grave`: Toggle scratchpad"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + S` / `Super + Shift + Grave`: Move window to scratchpad"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Alt + Arrows`: Move workspaces to directional monitor"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Arrow`: Move focus to window in direction of arrow"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Arrow`: Swap window with another in direction of arrow"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Minus`: Expand window left"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Equal`: Shrink window left"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Minus`: Shrink window up"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Equal`: Expand window down"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + Minus/Equal`: Same resizing in smaller steps"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Minus/Equal`: Same resizing in bigger steps"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + Home`: Save window width"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Home`: Restore saved window width"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Left Mouse`: Drag window around"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Right Mouse`: Resize window"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Scroll Wheel`: Scroll through workspaces"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + G`: Toggle window grouping"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + G`: Move window out of grouping"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + Tab`: Cycle between windows in grouping"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + Shift + Tab`: Cycle backward between windows in grouping"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + 1/2/3/4/5`: Jump to specific window in grouping"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + Arrow`: Move window into grouping in direction of arrow"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Left/Right`: Move between windows inside a tiling group"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Z`: Zoom in on screen (repeat for more zoom)"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Alt + Z`: Zoom fully out from screen"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + /`: Step forward through monitor scaling options"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + /`: Step backward through monitor scaling options"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Tab`: Cycle forward through windows on the active workspace"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Shift + Tab`: Cycle backward through windows on the active workspace"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + Alt + Tab`: Cycle focus forward through monitors"
 },
 {
  "page": "Hotkeys",
  "section": "Navigating",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + Alt + Shift + Tab`: Cycle focus backwards through monitors"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + A`: Audio panel"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + B`: Bluetooth panel"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + W`: Wifi/network panel"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + D`: Display panel"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + P`: Power panel"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Alt + D`: Calendar panel"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + 1-9`: Toggle bar panel by position"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + S`: Share menu (via LocalSend)"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + T`: Activity (btop)"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + C`: Capture controls (screenshot/-recording/picker)"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + O`: Toggle menu"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + H`: Hardware menu"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Q`: Calculator"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + E`: Emoji picker"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + .`: Transcode media"
 },
 {
  "page": "Hotkeys",
  "section": "System controls",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Ctrl + A`: Pick an AI agent"
 },
 {
  "page": "Hotkeys",
  "section": "Adjustments",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Shift + Brightness Up`: Maximum screen brightness"
 },
 {
  "page": "Hotkeys",
  "section": "Adjustments",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Shift + Brightness Down`: Minimum screen brightness"
 },
 {
  "page": "Hotkeys",
  "section": "Adjustments",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Brightness Up/Down`: Precise 1% brightness changes"
 },
 {
  "page": "Hotkeys",
  "section": "Adjustments",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Volume Up/Down`: Precise 1% volume changes"
 },
 {
  "page": "Hotkeys",
  "section": "Adjustments",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Play`: Next track"
 },
 {
  "page": "Hotkeys",
  "section": "Adjustments",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Shift + Play`: Previous track"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Return`: Terminal"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + Return`: Tmux terminal"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Return`: Herdr (agent manager)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Return`: Browser"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Alt + B`: Browser (private/incognito)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + F`: File manager"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Alt + F`: File manager in cwd of terminal"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + M`: Music (Spotify)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Alt + M`: Music (cliamp)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + /`: Password manager (1password)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + N`: Editor (Neovim)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + C`: Calendar (HEY)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + E`: Email (HEY)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Alt + E`: New email (HEY)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + A`: AI (ChatGPT)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Alt + A`: AI (Grok)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + G`: Messenger (Signal)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + P`: Google Photos"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + S`: Google Maps"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Alt + G`: Messenger (WhatsApp)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Ctrl + G`: Messenger (Google)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + D`: Docker (LazyDocker)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + O`: Obsidian"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + W`: Writing (Omawrite)"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + X`: X"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Alt + X`: X Compose"
 },
 {
  "page": "Hotkeys",
  "section": "Launching apps",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Y`: YouTube"
 },
 {
  "page": "Hotkeys",
  "section": "Universal clipboard",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + X`: Cut (not in terminal)"
 },
 {
  "page": "Hotkeys",
  "section": "Universal clipboard",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + V`: Clipboard manager"
 },
 {
  "page": "Hotkeys",
  "section": "Universal clipboard",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "Usually on Linux, you need `Ctrl + Shift + C/V` to copy'n'paste in the terminal and `Ctrl + C/V` to do it everywhere else."
 },
 {
  "page": "Hotkeys",
  "section": "Capture",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + C`: Capture menu (for keyboards w/o PrintScr button)"
 },
 {
  "page": "Hotkeys",
  "section": "Capture",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Print Screen`: Screenshot"
 },
 {
  "page": "Hotkeys",
  "section": "Capture",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Print Screen`: Screenrecord"
 },
 {
  "page": "Hotkeys",
  "section": "Capture",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Print Screen`: Color picker"
 },
 {
  "page": "Hotkeys",
  "section": "Capture",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Print Screen`: Text extraction to clipboard"
 },
 {
  "page": "Hotkeys",
  "section": "Capture",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + [`: Make webcam overlay smaller while recording"
 },
 {
  "page": "Hotkeys",
  "section": "Capture",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + ]`: Make webcam overlay larger while recording"
 },
 {
  "page": "Hotkeys",
  "section": "Capture",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Shift + L`: Copy current URL from webapp or Chromium"
 },
 {
  "page": "Hotkeys",
  "section": "Capture",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Shift + D`: Download the video on the current page to `~/Videos`"
 },
 {
  "page": "Hotkeys",
  "section": "Capture",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + X`: Start/stop dictation (requires Install > AI > Dictation)"
 },
 {
  "page": "Hotkeys",
  "section": "Capture",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "All capture options are also accessible under Trigger > Capture in the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Hotkeys",
  "section": "Notifications",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + ,`: Dismiss latest notification"
 },
 {
  "page": "Hotkeys",
  "section": "Notifications",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + ,`: Dismiss all notifications"
 },
 {
  "page": "Hotkeys",
  "section": "Notifications",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + ,`: Toggle silencing notifications"
 },
 {
  "page": "Hotkeys",
  "section": "Notifications",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Alt + ,`: Invoke most recent notification"
 },
 {
  "page": "Hotkeys",
  "section": "Notifications",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Alt + ,`: Open notification history"
 },
 {
  "page": "Hotkeys",
  "section": "Style",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Shift + Space`: Pick a new theme"
 },
 {
  "page": "Hotkeys",
  "section": "Style",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Space`: Pick theme background"
 },
 {
  "page": "Hotkeys",
  "section": "Style",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Backspace`: Toggle transparency on a window"
 },
 {
  "page": "Hotkeys",
  "section": "Style",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Backspace`: Toggle single-window square aspect"
 },
 {
  "page": "Hotkeys",
  "section": "Style",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "All style options are also accessible under Style in the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Hotkeys",
  "section": "Toggles",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + I`: Toggle locking on idle"
 },
 {
  "page": "Hotkeys",
  "section": "Toggles",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + N`: Toggle nightlight display temperature"
 },
 {
  "page": "Hotkeys",
  "section": "Toggles",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Delete`: Toggle laptop display on/off"
 },
 {
  "page": "Hotkeys",
  "section": "Toggles",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Alt + Delete`: Toggle laptop display mirroring"
 },
 {
  "page": "Hotkeys",
  "section": "Toggles",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Space`: Toggle the top bar"
 },
 {
  "page": "Hotkeys",
  "section": "Toggles",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Shift + Mute`: Switch to next audio output"
 },
 {
  "page": "Hotkeys",
  "section": "Toggles",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Shift + Play`: Switch to next media source"
 },
 {
  "page": "Hotkeys",
  "section": "Toggles",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Shift + Backspace`: Toggle window gaps"
 },
 {
  "page": "Hotkeys",
  "section": "Toggles",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Alt + F`: Toggle full screen desktop (top bar + window gaps)"
 },
 {
  "page": "Hotkeys",
  "section": "Reminders",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + R`: Set a reminder"
 },
 {
  "page": "Hotkeys",
  "section": "Reminders",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Alt + R`: See all reminders"
 },
 {
  "page": "Hotkeys",
  "section": "Reminders",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Shift + R`: Clear all reminders"
 },
 {
  "page": "Hotkeys",
  "section": "Notices",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Alt + T`: Show time as notification"
 },
 {
  "page": "Hotkeys",
  "section": "Notices",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Alt + B`: Show battery as notification"
 },
 {
  "page": "Hotkeys",
  "section": "Notices",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Alt + W`: Toggle weather as notification"
 },
 {
  "page": "Hotkeys",
  "section": "Tmux",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "The prefix key is `Ctrl + Space` (`Ctrl + B` also works)."
 },
 {
  "page": "Hotkeys",
  "section": "Panes",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Enter`: Split pane below (no prefix)"
 },
 {
  "page": "Hotkeys",
  "section": "Panes",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Shift + Enter`: Split pane beside (no prefix)"
 },
 {
  "page": "Hotkeys",
  "section": "Panes",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Escape`: Kill pane (no prefix)"
 },
 {
  "page": "Hotkeys",
  "section": "Panes",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + Alt + Arrows`: Move between panes"
 },
 {
  "page": "Hotkeys",
  "section": "Panes",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + Alt + Shift + Arrows`: Resize panes"
 },
 {
  "page": "Hotkeys",
  "section": "Windows",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + 1-9`: Go to specific window"
 },
 {
  "page": "Hotkeys",
  "section": "Windows",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Arrow Left/Right`: Move between windows"
 },
 {
  "page": "Hotkeys",
  "section": "Windows",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Shift + Arrow Left/Right`: Move window left/right"
 },
 {
  "page": "Hotkeys",
  "section": "Sessions",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Arrow Up/Down`: Move between sessions"
 },
 {
  "page": "Hotkeys",
  "section": "Ghostty Terminal",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + Shift + E`: New split below"
 },
 {
  "page": "Hotkeys",
  "section": "Ghostty Terminal",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + Shift + O`: New split besides"
 },
 {
  "page": "Hotkeys",
  "section": "Ghostty Terminal",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + Alt + Arrows`: Move between splits"
 },
 {
  "page": "Hotkeys",
  "section": "Ghostty Terminal",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Shift + Arrows`: Resize split by 10 lines"
 },
 {
  "page": "Hotkeys",
  "section": "Ghostty Terminal",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Super + Ctrl + Shift + Alt + Arrows`: Resize split by 100 lines"
 },
 {
  "page": "Hotkeys",
  "section": "Ghostty Terminal",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + Shift + T`: New tab"
 },
 {
  "page": "Hotkeys",
  "section": "Ghostty Terminal",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + Shift + Arrows`: Move between tabs"
 },
 {
  "page": "Hotkeys",
  "section": "Ghostty Terminal",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Alt + Numbers`: Go to specific tab"
 },
 {
  "page": "Hotkeys",
  "section": "Ghostty Terminal",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Shift + Pg Up/Down`: Scroll the history"
 },
 {
  "page": "Hotkeys",
  "section": "Ghostty Terminal",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + Left mouse`: Open link in browser"
 },
 {
  "page": "Hotkeys",
  "section": "File Manager",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + L`: Go to path"
 },
 {
  "page": "Hotkeys",
  "section": "Navigation",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + W W`: Jump between sidebar and editor"
 },
 {
  "page": "Hotkeys",
  "section": "Navigation",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Ctrl + Left/right arrow`: Change size of sidebar"
 },
 {
  "page": "Hotkeys",
  "section": "Navigation",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Shift + H`: Go to left file tab"
 },
 {
  "page": "Hotkeys",
  "section": "Navigation",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Shift + L`: Go to right file tab"
 },
 {
  "page": "Hotkeys",
  "section": "While in sidebar",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "`Shift + A`: Add new subdir in parent dir"
 },
 {
  "page": "Hotkeys",
  "section": "Quick Emojis",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "You can use `Super + Ctrl + E` to show a complete emoji picker that'll put the selection on the clipboard or you can use these quick access options."
 },
 {
  "page": "Hotkeys",
  "section": "Quick Completions",
  "url": "https://omarchy.org/manual/hotkeys/",
  "text": "You can add more of your own by editing `~/.XCompose`, then running `omarchy-restart-xcompose` in the terminal to get the changes picked up."
 },
 {
  "page": "Unified Clipboard & History",
  "section": "",
  "url": "https://omarchy.org/manual/unified-clipboard-history/",
  "text": "Note that most agent harnesses will use `Ctrl + V` for pasting images, but `Super + V` for pasting text."
 },
 {
  "page": "Unified Clipboard & History",
  "section": "Clipboard history",
  "url": "https://omarchy.org/manual/unified-clipboard-history/",
  "text": "You trigger it by `Super + Ctrl + V`, select your entry with return, and then that'll be placed on the clipboard ready to paste on `Super + V`."
 },
 {
  "page": "Reminders",
  "section": "",
  "url": "https://omarchy.org/manual/reminders/",
  "text": "You can do this via `Super + Ctrl + R`, seeing all the ones set via `Super + Ctrl + Alt + R`, and clearing all via `Super + Ctrl + Shift + R`."
 },
 {
  "page": "Reminders",
  "section": "",
  "url": "https://omarchy.org/manual/reminders/",
  "text": "You can also use the cli with `omarchy reminder 7 'Tea ready'`."
 },
 {
  "page": "Notices",
  "section": "Weather",
  "url": "https://omarchy.org/manual/notices/",
  "text": "You can pin it down with `omarchy weather location --set Malibu`, or be exact about it by adding coordinates: `omarchy weather location --set Malibu 34.0259,-118.7798`."
 },
 {
  "page": "Notices",
  "section": "Weather",
  "url": "https://omarchy.org/manual/notices/",
  "text": "Run `omarchy weather location` on its own to see where it thinks you are, and `--clear` to go back to auto-detection."
 },
 {
  "page": "Text Extraction & Dictation",
  "section": "Text Extraction",
  "url": "https://omarchy.org/manual/text-extraction-dictation/",
  "text": "Hit `Super + Ctrl + PrtScr` to select a region on the screen for text extraction."
 },
 {
  "page": "Screenshots & Recording",
  "section": "",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "If your keyboard doesn't have a Print Screen key at all, `Super + Ctrl + C` opens the same set as a menu."
 },
 {
  "page": "Screenshots & Recording",
  "section": "",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Alt + Print Screen`: Screenrecord (or stop the one that's running)"
 },
 {
  "page": "Screenshots & Recording",
  "section": "",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Super + Print Screen`: Colour picker"
 },
 {
  "page": "Screenshots & Recording",
  "section": "",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Super + Ctrl + Print Screen`: Extract text from a region"
 },
 {
  "page": "Screenshots & Recording",
  "section": "",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Super + Ctrl + C`: Capture menu"
 },
 {
  "page": "Screenshots & Recording",
  "section": "",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Super + Ctrl + .`: Transcode a picture or video"
 },
 {
  "page": "Screenshots & Recording",
  "section": "Screenshots",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "Hit `Print Screen` and the screen freezes so nothing shifts under you while you aim."
 },
 {
  "page": "Screenshots & Recording",
  "section": "Screenshots",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "Hit `Print Screen` again to dismiss the picker."
 },
 {
  "page": "Screenshots & Recording",
  "section": "Screenshots",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "The result goes two places at once: a PNG in your pictures directory, and the clipboard, so you can paste it straight into a chat window with `Super + V`."
 },
 {
  "page": "Screenshots & Recording",
  "section": "Screenshots",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "Click it (or hit `Super + Alt + ,` to invoke the last notification) and the shot opens in Tensaku, the annotation editor, where you can draw arrows and boxes on it before you send it."
 },
 {
  "page": "Screenshots & Recording",
  "section": "Driving the picker from the keyboard",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Ctrl + Return`: Capture the whole screen"
 },
 {
  "page": "Screenshots & Recording",
  "section": "Driving the picker from the keyboard",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Tab` / `Ctrl + Tab`: Highlight the next / previous window"
 },
 {
  "page": "Screenshots & Recording",
  "section": "Screen recording",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Alt + Print Screen` opens Trigger > Capture > Screenrecord, which asks what you want on the soundtrack: no audio, desktop audio, desktop plus microphone, or desktop plus microphone plus webcam."
 },
 {
  "page": "Screenshots & Recording",
  "section": "Screen recording",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "You can also stop with `Alt + Print Screen` again, or with the Stop Screenrecording entry under Trigger > Capture > Screenrecord, which only appears while something is actually recording."
 },
 {
  "page": "Screenshots & Recording",
  "section": "The webcam overlay",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Super + Alt + [`: Make the webcam overlay smaller"
 },
 {
  "page": "Screenshots & Recording",
  "section": "The webcam overlay",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Super + Alt + ]`: Make the webcam overlay larger"
 },
 {
  "page": "Screenshots & Recording",
  "section": "The webcam overlay",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "You can also call it directly with `omarchy-capture-webcam-resize small`, or `reset` to go back to medium."
 },
 {
  "page": "Screenshots & Recording",
  "section": "Text, QR codes, and colours",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Super + Ctrl + Print Screen` selects a region and OCRs it to the clipboard."
 },
 {
  "page": "Screenshots & Recording",
  "section": "Text, QR codes, and colours",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Super + Print Screen` (or Trigger > Capture > Color) turns the cursor into an eyedropper."
 },
 {
  "page": "Screenshots & Recording",
  "section": "Transcoding before you share",
  "url": "https://omarchy.org/manual/screenshots-recording/",
  "text": "`Super + Ctrl + .` (or Trigger > Transcode) fixes that."
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "The toggle menu",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "`Super + Ctrl + O` opens Trigger > Toggle directly, or you can walk there from the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "The toggle menu",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "From the terminal, the same switches are `omarchy toggle <thing>`."
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "The toggle menu",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "Run `omarchy toggle` on its own to see the whole group."
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "The toggle menu",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "`Super + Ctrl + N`: Night light. From a terminal: `omarchy toggle nightlight`"
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "The toggle menu",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "`Super + Ctrl + ,`: Silence notifications. From a terminal: `omarchy toggle notification silencing`"
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "The toggle menu",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "`Super + Ctrl + I`: Stay awake (no idle lock). From a terminal: `omarchy toggle idle`"
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "The toggle menu",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "`Super + Shift + Space`: Menu bar. From a terminal: `omarchy toggle bar`"
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "The toggle menu",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "The touchpad, touchscreen, and hybrid GPU switches live under Trigger > Hardware (`Super + Ctrl + H`) rather than under Toggle, since they only show up when you actually have that hardware."
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "Night light",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "`Super + Ctrl + N` warms the screen to 4000K, and hitting it again puts it back to 6500K."
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "Do not disturb",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "`Super + Ctrl + ,` silences notifications."
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "Idle",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "To stop locking on idle entirely, `Super + Ctrl + I`, or `omarchy toggle idle`, flips stay awake on, and the coffee cup indicator appears in the bar."
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "Idle",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "`omarchy toggle idle status` prints the current state as JSON if you need it from a script."
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "The screensaver",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "You can start it on demand from System > Screensaver (`Super + Esc`), which forces it up even if you've turned the idle screensaver off."
 },
 {
  "page": "Toggles, Idle & the Screensaver",
  "section": "The screensaver",
  "url": "https://omarchy.org/manual/toggles-idle-screensaver/",
  "text": "`omarchy toggle screensaver` is what turns the idle one off, if you'd rather go straight from working to locked."
 },
 {
  "page": "Omarchy CLI",
  "section": "",
  "url": "https://omarchy.org/manual/omarchy-cli/",
  "text": "Omarchy is usually controlled through the hotkeys and the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Omarchy CLI",
  "section": "",
  "url": "https://omarchy.org/manual/omarchy-cli/",
  "text": "Every command takes `--help` too, whether you ask a whole group (`omarchy capture --help`) or a single command (`omarchy capture screenshot --help`)."
 },
 {
  "page": "Terminal",
  "section": "",
  "url": "https://omarchy.org/manual/terminal/",
  "text": "You start a new terminal using `Super + Return`."
 },
 {
  "page": "Terminal",
  "section": "Tmux",
  "url": "https://omarchy.org/manual/terminal/",
  "text": "You start a new Tmux session in a fresh terminal using `Super + Alt + Return`, and because Tmux is a persistent process, you can resume your session even if you close that terminal."
 },
 {
  "page": "Neovim",
  "section": "LazyVim Basics",
  "url": "https://omarchy.org/manual/neovim/",
  "text": "`Ctrl + W W` - Hop from the file tree to the editor and back."
 },
 {
  "page": "Neovim",
  "section": "LazyVim Basics",
  "url": "https://omarchy.org/manual/neovim/",
  "text": "`Shift + H` - Move left between the open tabs (vim calls them buffers)."
 },
 {
  "page": "Neovim",
  "section": "LazyVim Basics",
  "url": "https://omarchy.org/manual/neovim/",
  "text": "`Shift + L` - Move right between the open tabs."
 },
 {
  "page": "Neovim",
  "section": "LazyVim Basics",
  "url": "https://omarchy.org/manual/neovim/",
  "text": "While you're in the file tree (`Space E` to reveal, `Ctrl + W W` to hop over there), you can add a new file with `a` or a new directory with `A`."
 },
 {
  "page": "Neovim",
  "section": "Starting Neovim",
  "url": "https://omarchy.org/manual/neovim/",
  "text": "You can start Neovim using `Super + Shift + N` (the binding launches your default editor, which is Neovim out of the box), but it's usually easier to drive it from the terminal by navigating to the directory you wish to work in and typing `n`."
 },
 {
  "page": "AI",
  "section": "",
  "url": "https://omarchy.org/manual/ai/",
  "text": "To wrap an additional CLI the same way, run `omarchy-mise-install <package> [command-name]`."
 },
 {
  "page": "AI",
  "section": "",
  "url": "https://omarchy.org/manual/ai/",
  "text": "The stubs are kept current along with everything else mise manages when you run `omarchy update` (or the `mup` alias)."
 },
 {
  "page": "AI",
  "section": "The default agent",
  "url": "https://omarchy.org/manual/ai/",
  "text": "Pick your default agent with `omarchy default agent <name>` or under Setup > Defaults > Agent in the Omarchy Menu (`Super + Space`)."
 },
 {
  "page": "AI",
  "section": "The default agent",
  "url": "https://omarchy.org/manual/ai/",
  "text": "You can also launch it straight into a task with `omarchy agent prompt \"Review this project\"`."
 },
 {
  "page": "AI",
  "section": "The agents panel",
  "url": "https://omarchy.org/manual/ai/",
  "text": "The usage records behind it are regenerated every 15 minutes by `omarchy agent usage-update`, and the panel can even merge usage from your other machines via a synced folder."
 },
 {
  "page": "AI",
  "section": "Crash diagnosis",
  "url": "https://omarchy.org/manual/ai/",
  "text": "You can also run it by hand against any PID from `coredumpctl list` with `omarchy agent crash <pid>`."
 },
 {
  "page": "AI",
  "section": "Crash diagnosis",
  "url": "https://omarchy.org/manual/ai/",
  "text": "Turn it off under Trigger > Toggle > Crash Capture (or with `omarchy toggle crash-capture`) and the notifications stop; `omarchy agent crash <pid>` still works by hand."
 },
 {
  "page": "AI",
  "section": "Crash diagnosis",
  "url": "https://omarchy.org/manual/ai/",
  "text": "`omarchy crash mute hyprland` stops the notifications for that program only, `omarchy crash mute hyprland off` brings them back, and `omarchy crash mute` on its own lists what you've muted."
 },
 {
  "page": "AI",
  "section": "Crash diagnosis",
  "url": "https://omarchy.org/manual/ai/",
  "text": "Quote a name with a space in it, as in `omarchy crash mute 'Some App'`."
 },
 {
  "page": "Development Tools",
  "section": "Alternative Editors",
  "url": "https://omarchy.org/manual/development-tools/",
  "text": "Omarchy ships with Neovim by default, but if you'd like something a bit more mainstream and familiar, you can run the Omarchy Menu (`Super + Space`) and see the options under Install > Editor."
 },
 {
  "page": "Development Tools",
  "section": "Environment",
  "url": "https://omarchy.org/manual/development-tools/",
  "text": "Omarchy supports setting up a whole host of development environments through the Install > Development section of the Omarchy Menu (`Super + Space`)."
 },
 {
  "page": "Development Tools",
  "section": "Docker",
  "url": "https://omarchy.org/manual/development-tools/",
  "text": "Remember to checkout the Lazydocker command to manage your containers in a cool TUI using `Super + Shift + D`; it asks for authorization the first time unless you have enabled sudoless Docker."
 },
 {
  "page": "Shell Tools",
  "section": "fzf",
  "url": "https://omarchy.org/manual/shell-tools/",
  "text": "You can use `Ctrl + R` to use fzf to fuzzy find through your command history."
 },
 {
  "page": "Shell Functions",
  "section": "SSH reconnection",
  "url": "https://omarchy.org/manual/shell-functions/",
  "text": "`ssh` itself is wrapped in a function that cleans up the terminal if a connection dies while a remote tmux, Herdr, or editor has claimed it, and then automatically reconnects when an interactive session drops (Ctrl-C stops the retry loop)."
 },
 {
  "page": "TUIs",
  "section": "Lazydocker",
  "url": "https://omarchy.org/manual/tuis/",
  "text": "You can start it with `Super + Shift + D`."
 },
 {
  "page": "TUIs",
  "section": "Btop",
  "url": "https://omarchy.org/manual/tuis/",
  "text": "Omarchy calls it Activity, and you start it by hitting `Super + Ctrl + T`."
 },
 {
  "page": "TUIs",
  "section": "Herdr",
  "url": "https://omarchy.org/manual/tuis/",
  "text": "You start it (or reattach to your existing session) with `Super + Ctrl + Return`."
 },
 {
  "page": "TUIs",
  "section": "Herdr",
  "url": "https://omarchy.org/manual/tuis/",
  "text": "Omarchy ships a Herdr configuration that mirrors its Tmux config, so the prefix key is `Ctrl + Space` here too."
 },
 {
  "page": "TUIs",
  "section": "Herdr",
  "url": "https://omarchy.org/manual/tuis/",
  "text": "You can browse all the keybindings with `Super + Ctrl + K`."
 },
 {
  "page": "TUIs",
  "section": "Fastfetch",
  "url": "https://omarchy.org/manual/tuis/",
  "text": "Omarchy has packaged this as About in the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "TUIs",
  "section": "Disk Usage",
  "url": "https://omarchy.org/manual/tuis/",
  "text": "When the drive fills up and you have no idea what's eating it, launch Disk Usage from the app launcher (`Super + Space`)."
 },
 {
  "page": "TUIs",
  "section": "Cliamp",
  "url": "https://omarchy.org/manual/tuis/",
  "text": "Launch it with `Super + Shift + Alt + M`, or from the Omarchy menu under Apps."
 },
 {
  "page": "TUIs",
  "section": "What about Wi-Fi and Bluetooth?",
  "url": "https://omarchy.org/manual/tuis/",
  "text": "Click the Wi-Fi icon in the top bar (or hit `Super + Ctrl + W`) to see networks and connect, and click the Bluetooth icon (or hit `Super + Ctrl + B`) to pair and connect devices."
 },
 {
  "page": "TUIs",
  "section": "Adding your own",
  "url": "https://omarchy.org/manual/tuis/",
  "text": "Go to Install > TUI in the Omarchy menu (`Super + Space`), give it a name, a launch command, a window style, and an icon, and it'll show up in the app launcher like any other application."
 },
 {
  "page": "GUIs",
  "section": "Files",
  "url": "https://omarchy.org/manual/guis/",
  "text": "`Super + Shift + F` opens it, and `Super + Shift + Alt + F` opens it in the directory your terminal is sitting in, which saves a lot of clicking."
 },
 {
  "page": "GUIs",
  "section": "Files",
  "url": "https://omarchy.org/manual/guis/",
  "text": "`Ctrl + L` lets you type a path, and hitting `Space` on any file gives you a quick preview without opening anything."
 },
 {
  "page": "GUIs",
  "section": "Files",
  "url": "https://omarchy.org/manual/guis/",
  "text": "For anything more involved, formatting a drive, checking SMART health, creating partitions, launch Disks from the app launcher (`Super + Space`)."
 },
 {
  "page": "GUIs",
  "section": "Obsidian",
  "url": "https://omarchy.org/manual/guis/",
  "text": "You start Obsidian with `Super + Shift + O`."
 },
 {
  "page": "GUIs",
  "section": "Omawrite",
  "url": "https://omarchy.org/manual/guis/",
  "text": "You start Omawrite with `Super + Shift + W`."
 },
 {
  "page": "GUIs",
  "section": "Pinta",
  "url": "https://omarchy.org/manual/guis/",
  "text": "You start Pinta via the application launcher (`Super + Space`)."
 },
 {
  "page": "GUIs",
  "section": "Aether",
  "url": "https://omarchy.org/manual/guis/",
  "text": "You start Aether via the application launcher (`Super + Space`)."
 },
 {
  "page": "GUIs",
  "section": "LocalSend",
  "url": "https://omarchy.org/manual/guis/",
  "text": "You can open the Share menu on `Super + Ctrl + S` or under Trigger > Share in the Omarchy menu."
 },
 {
  "page": "GUIs",
  "section": "LibreOffice",
  "url": "https://omarchy.org/manual/guis/",
  "text": "You start LibreOffice via the application launcher (`Super + Space`)."
 },
 {
  "page": "GUIs",
  "section": "Omacalc",
  "url": "https://omarchy.org/manual/guis/",
  "text": "You start Omacalc with `Super + Ctrl + Q` (or the calculator key, if your keyboard has one)."
 },
 {
  "page": "GUIs",
  "section": "Signal",
  "url": "https://omarchy.org/manual/guis/",
  "text": "You start Signal with `Super + Shift + G`."
 },
 {
  "page": "GUIs",
  "section": "mpv",
  "url": "https://omarchy.org/manual/guis/",
  "text": "You start mpv via the application launcher (`Super + Space`) or just double-click on a video in the file manager."
 },
 {
  "page": "GUIs",
  "section": "OBS Studio",
  "url": "https://omarchy.org/manual/guis/",
  "text": "You start OBS Studio via the application launcher (`Super + Space`)."
 },
 {
  "page": "GUIs",
  "section": "Kdenlive",
  "url": "https://omarchy.org/manual/guis/",
  "text": "You start Kdenlive via the application launcher (`Super + Space`)."
 },
 {
  "page": "GUIs",
  "section": "Omacut",
  "url": "https://omarchy.org/manual/guis/",
  "text": "You start Omacut via the application launcher (`Super + Space`)."
 },
 {
  "page": "Browsers",
  "section": "Copy URL and Download Video",
  "url": "https://omarchy.org/manual/browsers/",
  "text": "Copy URL puts the current tab's address on your clipboard with `Alt + Shift + L`."
 },
 {
  "page": "Browsers",
  "section": "Copy URL and Download Video",
  "url": "https://omarchy.org/manual/browsers/",
  "text": "Download Video grabs the video playing on the page you're looking at with `Alt + Shift + D`."
 },
 {
  "page": "Commercial apps/services",
  "section": "1Password",
  "url": "https://omarchy.org/manual/commercial-apps-services/",
  "text": "You start 1Password with `Super + Shift + /`."
 },
 {
  "page": "Commercial apps/services",
  "section": "Spotify",
  "url": "https://omarchy.org/manual/commercial-apps-services/",
  "text": "You start Spotify using `Super + Shift + M`."
 },
 {
  "page": "Web Apps",
  "section": "",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "You can add your own web apps using Install > Web App in the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Web Apps",
  "section": "",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "When you're in a web app, you can copy the current URL to the clipboard using `Shift + Alt + L`."
 },
 {
  "page": "Web Apps",
  "section": "HEY",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "You can start HEY Email using `Super + Shift + E`, jump straight to composing a new email using `Super + Shift + Alt + E`, and start HEY Calendar using `Super + Shift + C`."
 },
 {
  "page": "Web Apps",
  "section": "Basecamp",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "You can start Basecamp using the application launcher (`Super + Space`)"
 },
 {
  "page": "Web Apps",
  "section": "ChatGPT",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "You can start ChatGPT using `Super + Shift + A`."
 },
 {
  "page": "Web Apps",
  "section": "Grok",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "You can start Grok using `Super + Shift + Alt + A`."
 },
 {
  "page": "Web Apps",
  "section": "WhatsApp",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "You can start WhatsApp using `Super + Shift + Alt + G`."
 },
 {
  "page": "Web Apps",
  "section": "Google apps",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "You can start Google Messages using `Super + Shift + Ctrl + G`, Google Photos using `Super + Shift + P`, and Google Maps using `Super + Shift + S`."
 },
 {
  "page": "Web Apps",
  "section": "Google apps",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "Google Contacts is available through the app launcher (`Super + Space`)."
 },
 {
  "page": "Web Apps",
  "section": "X",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "You can start X using `Super + Shift + X` and go straight to writing a new post with `Super + Shift + Alt + X`."
 },
 {
  "page": "Web Apps",
  "section": "YouTube",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "You can start YouTube using `Super + Shift + Y`."
 },
 {
  "page": "Web Apps",
  "section": "Zoom",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "You start Zoom using the application launcher (`Super + Space`)."
 },
 {
  "page": "Web Apps",
  "section": "Discord",
  "url": "https://omarchy.org/manual/web-apps/",
  "text": "You start Discord using the application launcher (`Super + Space`)."
 },
 {
  "page": "Gaming",
  "section": "",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "All gaming installers live under Install > Gaming in the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Gaming",
  "section": "Steam",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "Install Steam by selecting Install > Gaming > Steam from the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Gaming",
  "section": "Steam",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "After you've installed it, you'll be able to launch Steam with `Super + Space`."
 },
 {
  "page": "Gaming",
  "section": "RetroArch",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "Install RetroArch by selecting Install > Gaming > RetroArch from the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Gaming",
  "section": "RetroArch",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "Launch RetroArch with `Super + Space` and typing `retro`."
 },
 {
  "page": "Gaming",
  "section": "RetroArch",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "You can also give a favorite game its own entry in the app launcher with Install > Gaming > RetroArch Game Launcher, which lets you pick a core and a ROM, and jump straight into the game from `Super + Space`."
 },
 {
  "page": "Gaming",
  "section": "Xbox Cloud Gaming",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "Install the Xbox Cloud Gaming web app by selecting Install > Gaming > Xbox Cloud Gaming from the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Gaming",
  "section": "NVIDIA GeForce Now",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "Install the cloud-gaming service NVIDIA GeForce NOW by selecting Install > Gaming > NVIDIA GeForce NOW from the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Gaming",
  "section": "Minecraft",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "Install Minecraft by selecting Install > Gaming > Minecraft from the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Gaming",
  "section": "Xbox Controllers",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "Install support for Bluetooth Xbox controllers by selecting Install > Gaming > Xbox Controllers from the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Gaming",
  "section": "Xbox Controllers",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "Pair the controllers via Bluetooth (`Super + Ctrl + B`) and they'll work in all your games."
 },
 {
  "page": "Gaming",
  "section": "Moonlight (Game streaming from a PC)",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "You can also turn an Omarchy machine into the host by running `omarchy install service sunshine`, which installs Sunshine and opens the Moonlight streaming ports for your LAN and Tailscale."
 },
 {
  "page": "Gaming",
  "section": "Battle.net",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "Install Battle.net by selecting Install > Gaming > Battle.net from the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Gaming",
  "section": "Lutris (Windows games)",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "Install Lutris by selecting Install > Gaming > Lutris from the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Gaming",
  "section": "Heroic Launcher (Epic Games)",
  "url": "https://omarchy.org/manual/gaming/",
  "text": "Install the Heroic Launcher by selecting Install > Gaming > Heroic (Epic Games) from the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Windows VM",
  "section": "",
  "url": "https://omarchy.org/manual/windows-vm/",
  "text": "You can install it using Install > Windows from the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Windows VM",
  "section": "Using it",
  "url": "https://omarchy.org/manual/windows-vm/",
  "text": "If you'd rather leave it running, say you've got something working away in there, launch it with `omarchy windows vm launch --keep-alive` instead."
 },
 {
  "page": "Windows VM",
  "section": "Limits and licensing",
  "url": "https://omarchy.org/manual/windows-vm/",
  "text": "You can change the resource allocation later by re-running `omarchy-windows-vm install`, which rewrites the VM's configuration from your answers."
 },
 {
  "page": "Other Packages",
  "section": "",
  "url": "https://omarchy.org/manual/other-packages/",
  "text": "You install a new Arch package by going to Install > Package in the Omarchy menu (`Super + Space`) and typing the package you want."
 },
 {
  "page": "Updates",
  "section": "",
  "url": "https://omarchy.org/manual/updates/",
  "text": "Omarchy and your packages are kept up to date via Update > Omarchy in the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Updates",
  "section": "Four channels",
  "url": "https://omarchy.org/manual/updates/",
  "text": "You can switch between channels using Update > Channel from the Omarchy menu (or `omarchy-channel-set` in the terminal)."
 },
 {
  "page": "Updates",
  "section": "Rolling back bad updates",
  "url": "https://omarchy.org/manual/updates/",
  "text": "If somehow your configuration files have been corrupted, you can also perform an Omarchy reinstall using `omarchy reinstall` in the terminal."
 },
 {
  "page": "Dotfiles",
  "section": "",
  "url": "https://omarchy.org/manual/dotfiles/",
  "text": "The key configs can be edited straight from the Omarchy menu (`Super + Space`), like Setup > Monitors, Setup > Keybindings, Setup > Input, and Setup > Config > [file]."
 },
 {
  "page": "Dotfiles",
  "section": "Running scripts on system events",
  "url": "https://omarchy.org/manual/dotfiles/",
  "text": "To install a script you've written elsewhere, use `omarchy hook install post-boot ~/my-hook`, which copies it in and makes it executable."
 },
 {
  "page": "Dotfiles",
  "section": "Adding your own menu entries",
  "url": "https://omarchy.org/manual/dotfiles/",
  "text": "The Omarchy menu (`Super + Space`) can be extended with your own rows by editing `~/.config/omarchy/extensions/omarchy-menu.jsonc`."
 },
 {
  "page": "Shell Plugins",
  "section": "",
  "url": "https://omarchy.org/manual/shell-plugins/",
  "text": "The Omarchy desktop runs as a single long-lived Quickshell process called `omarchy-shell`, and almost everything you see on screen is a plugin inside it."
 },
 {
  "page": "Monitors",
  "section": "",
  "url": "https://omarchy.org/manual/monitors/",
  "text": "You can also quickly step through the major monitor scaling ratios (1x, 1.25x, 1.6x, 2x, 3x, 4x) using `Super + /` to go higher and `Super + Alt + /` to go lower."
 },
 {
  "page": "Monitors",
  "section": "Making text bigger or smaller",
  "url": "https://omarchy.org/manual/monitors/",
  "text": "Run it without an argument to see where you're at, and `omarchy display text size reset` to go back to the default."
 },
 {
  "page": "Monitors",
  "section": "Extending and mirroring laptop displays",
  "url": "https://omarchy.org/manual/monitors/",
  "text": "You can also control this manually using Trigger > Hardware in the Omarchy menu or `Super + Ctrl + Delete`."
 },
 {
  "page": "Keyboard, Mouse, Trackpad",
  "section": "",
  "url": "https://omarchy.org/manual/keyboard-mouse-trackpad/",
  "text": "You change all of it in `~/.config/hypr/input.lua`, which you can also reach via Setup > Input in the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Networking",
  "section": "",
  "url": "https://omarchy.org/manual/networking/",
  "text": "Networking in Omarchy is handled by NetworkManager, and you drive it from the network icon in the top bar or with `Super + Ctrl + W`."
 },
 {
  "page": "Networking",
  "section": "",
  "url": "https://omarchy.org/manual/networking/",
  "text": "If you'd rather stay in the terminal, `nmtui` gives you the same controls, and there's an `omarchy network` command group too."
 },
 {
  "page": "Networking",
  "section": "Sharing your Wi-Fi",
  "url": "https://omarchy.org/manual/networking/",
  "text": "If you actually need the password itself, `omarchy network password <interface>` prints it."
 },
 {
  "page": "Networking",
  "section": "DNS",
  "url": "https://omarchy.org/manual/networking/",
  "text": "From the terminal, `omarchy dns` prints the current provider and `omarchy dns Cloudflare` sets one."
 },
 {
  "page": "Networking",
  "section": "Pinning the Wi-Fi band",
  "url": "https://omarchy.org/manual/networking/",
  "text": "`omarchy network band` shows which band you're on, and `omarchy network band 5` pins it."
 },
 {
  "page": "Networking",
  "section": "How fast is it?",
  "url": "https://omarchy.org/manual/networking/",
  "text": "From the terminal it's `omarchy network speedtest down` or `up`."
 },
 {
  "page": "Networking",
  "section": "Tailscale",
  "url": "https://omarchy.org/manual/networking/",
  "text": "The terminal equivalent is `omarchy tailscale send <machine> [file...]`, and files sent to you land in `~/Downloads` automatically."
 },
 {
  "page": "System sleep",
  "section": "Power profiles",
  "url": "https://omarchy.org/manual/system-sleep/",
  "text": "You can see what your machine offers with `omarchy powerprofiles list`, and set the one you want for the state you're currently in with `omarchy powerprofiles set autodetect power-saver`."
 },
 {
  "page": "System sleep",
  "section": "Power profiles",
  "url": "https://omarchy.org/manual/system-sleep/",
  "text": "To set the other state without unplugging anything, name it directly: `omarchy powerprofiles set battery power-saver`."
 },
 {
  "page": "System sleep",
  "section": "Toggle suspend",
  "url": "https://omarchy.org/manual/system-sleep/",
  "text": "You toggle suspend by running `omarchy toggle suspend` from the terminal."
 },
 {
  "page": "System sleep",
  "section": "Toggle hibernation",
  "url": "https://omarchy.org/manual/system-sleep/",
  "text": "You set up hibernation by running `omarchy hibernation setup` from the terminal."
 },
 {
  "page": "System sleep",
  "section": "Toggle hibernation",
  "url": "https://omarchy.org/manual/system-sleep/",
  "text": "When set up, you'll see the hibernate option under System (or `Super + Esc`), and then you can see if it works consistently on your system."
 },
 {
  "page": "System sleep",
  "section": "Toggle hibernation",
  "url": "https://omarchy.org/manual/system-sleep/",
  "text": "If not, you can remove it again by running `omarchy hibernation remove`."
 },
 {
  "page": "Hardware authentication",
  "section": "Fingerprint authentication",
  "url": "https://omarchy.org/manual/hardware-authentication/",
  "text": "You can use this with Omarchy by running Setup > Security > Fingerprint in the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Fonts",
  "section": "",
  "url": "https://omarchy.org/manual/fonts/",
  "text": "You can change this through the Style > Font menu in the Omarchy menu (`Super + Space`)."
 },
 {
  "page": "Backgrounds",
  "section": "",
  "url": "https://omarchy.org/manual/backgrounds/",
  "text": "Hit `Super + Shift + F` to start another file manager, find your background, copy it over."
 },
 {
  "page": "Branding",
  "section": "Boot unlock",
  "url": "https://omarchy.org/manual/branding/",
  "text": "You can use `omarchy plymouth preview` to see what your custom logo and colors would look like."
 },
 {
  "page": "Branding",
  "section": "Boot unlock",
  "url": "https://omarchy.org/manual/branding/",
  "text": "If you want to revert, you can use `omarchy plymouth reset`."
 },
 {
  "page": "Common tweaks",
  "section": "",
  "url": "https://omarchy.org/manual/common-tweaks/",
  "text": "If you really screw everything up, you can reset all configs via `omarchy-reinstall`."
 },
 {
  "page": "Common tweaks",
  "section": "Remove window gaps",
  "url": "https://omarchy.org/manual/common-tweaks/",
  "text": "On laptop displays, some people prefer not to waste any pixels on window gaps (or even a top bar, which you can toggle off with `Super + Shift + Space`)."
 },
 {
  "page": "Making your own theme",
  "section": "What an installed theme can contain",
  "url": "https://omarchy.org/manual/making-your-own-theme/",
  "text": "Omarchy tells the two apart by whether the theme has its own git repo inside it, which is what `omarchy theme install` leaves behind when it clones."
 },
 {
  "page": "Troubleshooting",
  "section": "I broke my system with an update!",
  "url": "https://omarchy.org/manual/troubleshooting/",
  "text": "If that doesn't work, use `omarchy-debug` to share with your problem on #omarchy-help in the Discord."
 },
 {
  "page": "Troubleshooting",
  "section": "Why are some apps so large on my display?",
  "url": "https://omarchy.org/manual/troubleshooting/",
  "text": "For Spotify, you can use `Ctrl + Minus` to shrink the UI (and `Ctrl + Plus` to make it bigger)."
 },
 {
  "page": "Troubleshooting",
  "section": "My laptop speakers sound off",
  "url": "https://omarchy.org/manual/troubleshooting/",
  "text": "`omarchy audio tuning status` tells you whether one is active on your machine, and `omarchy audio tuning off` turns it off if you'd rather hear the speakers raw."
 },
 {
  "page": "FAQ",
  "section": "How do I check how fast my disk is?",
  "url": "https://omarchy.org/manual/faq/",
  "text": "Trigger > Speed Test > Disk Speed Test measures live read and write speed on your drive, or `omarchy disk speedtest` from the terminal."
 },
 {
  "page": "FAQ",
  "section": "How do I add a printer?",
  "url": "https://omarchy.org/manual/faq/",
  "text": "Printing is set up and running out of the box, and you add each printer yourself from Print Settings in the app launcher (`Super + Space`)."
 },
 {
  "page": "System snapshots",
  "section": "",
  "url": "https://omarchy.org/manual/system-snapshots/",
  "text": "We create snapshots automatically on every Omarchy update, but should you want to create your own, you can use `omarchy-snapshot create`."
 },
 {
  "page": "System snapshots",
  "section": "",
  "url": "https://omarchy.org/manual/system-snapshots/",
  "text": "Alternatively, you can utilize `omarchy-snapshot restore`."
 }
];
